version: 2
updates:

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
          time: "06:00"
          timezone: "Europe/Rome"
      commit-message:
          prefix: "🔀"
      labels: ["github-actions"]
      target-branch: "master"
      reviewers:
        - "Alexdelli"

    - package-ecosystem: "gitsubmodule"
      directory: "/"
      schedule:
          interval: "daily"
          time: "06:00"
          timezone: "Europe/Rome"
      commit-message:
          prefix: "🔀"
      labels: ["submodule"]
      target-branch: "master"
      ignore:
        - dependency-name: "docs/blog.wiki"
      reviewers:
        - "Alexdelli"
